### ISSUE TITLE
Leader redirecting is non-trivial

### ISSUE THREAD

**Issue by alex8937** [SCPD-Project/raft-kv-store#22]
Leader redirecting seems to be more complicated than what we thought. Though `raft.Leader` can return the RAFT server address, it is different from listening address the server uses to receive PUT/DELETE/GET/TXN.

Possible solution: maintain another key value store to save the address information on each server with RAFT consensus.

**Comment by varks** [comment]
I had a similar requirement for coordinator to reach the followers. Coordinator maintains the mapping for the listening address of all the shards. I have it working now. We can talk more during our sync up next week.

**Comment by supriya-premkumar** [comment]
>  listening address of all the shards
I thought implementing multiple shards was on my plate. Issue #15

**Comment by supriya-premkumar** [comment]
@varks ^^
