### ISSUE TITLE
Random timeout for each txn

### ISSUE THREAD

**Issue by alex8937** [SCPD-Project/raft-kv-store#80]
https://github.com/SCPD-Project/raft-kv-store/pull/79 is to resolve the cohort crash and potentially lock held after any txn:  

There is still one question remained. For example, assuming there are N txns wants to set x and y 
at the same time, and x and y are in different shards. There could be the case that `txn i` grabs the lock of x but fails to get y, and `txn j` grabs the lock of y but fails to get x. All the rest txns fail to get both of them. In this case, all txns will be aborted and none txn will go through.

A quick fix will be to have random timeout for each txn so the txn with the txn with the longest timeout will keep trying to get the lock until other finish.

**Comment by varks** [comment]
I believe you are referring to random timeouts for each transaction on the client side.

**Comment by alex8937** [comment]
> I believe you are referring to random timeouts for each transaction on the client side.

Not necessary. The current cmap has a constant timeout. Instead, what I am proposing is for each txid generated by the coordinator, a random trylocktimeout will be attached with the txn. 

A random retry waiting time can be done on the client side as well.

**Comment by varks** [comment]
I would suggest do random retries on client. It doesn't look clean to have random trylock timeouts.

**Comment by alex8937** [comment]
txid depending trylock timeouts will ensure one of the N txn will succeed on the first trial with high probability. 

On the other hand, client random retries need to be coupled with the current retries of `xfer` if added, which is potentially more work.
